name: "Build CI/CD"
description: "Build and deploy Flowave"
runs:
  using: "composite"
  steps:
    - name: Build
      env:
          MAVEN_OPTS: "-Xmx8g"
      shell: bash
      run: |
        mvn -B -e -U deploy -DskipTests=true -DskipITs=true -s ./settings.xml