name: "Build CI/CD"
description: "Build and deploy Fluxnova"
inputs:
  branch:
    description: 'Branch name to determine build or deploy'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: Build or Deploy
      env:
        MAVEN_OPTS: "-Xmx8g"
      shell: bash
      run: |
        if [[ "${{ inputs.branch }}" == "main" ]]; then
          mvn -B -e -U deploy -DskipTests=true -DskipITs=true -s ./settings.xml
        else
          mvn -B -e -U clean install -DskipTests=true -DskipITs=true
        fi
